apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    #command:
    #  - sleep
    #  - "3600"
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
